### ISSUE TITLE
No generator for _build/stage1/libraries/ghc-prim/autogen/GHC/Prim.hs.

### ISSUE THREAD

**Issue by alexbiehl** [snowleopard/hadrian#293] opened 2016-11-08 08:23 UTC
Invoking `hadrian/build.stack.sh` on a fresh copy of GHC results in above error message: 

```
| Remove file _build/stage1/compiler/libHSghc-8.1_p.a
shakeArgsWith   0.000s    0%                           
Function shake  0.462s   13%  ====                     
Database read   0.446s   12%  ====                     
With database   0.013s    0%                           
Running rules   2.601s   73%  =========================
Total           3.522s  100%                           
Error when running Shake build system:
* inplace/bin/ghctags
* _build/stage1/compiler/libHSghc-8.1_p.a
* _build/stage1/compiler/GHCi.p_o
* _build/stage1/compiler/GHCi.p_o _build/stage1/compiler/GHCi.p_hi
* _build/stage1/libraries/ghci/GHCi/Message.p_hi
* _build/stage1/libraries/ghci/GHCi/Message.p_o _build/stage1/libraries/ghci/GHCi/Message.p_hi
* _build/stage1/libraries/ghci/GHCi/InfoTable.p_hi
* _build/stage1/libraries/ghci/GHCi/InfoTable.p_o _build/stage1/libraries/ghci/GHCi/InfoTable.p_hi
* _build/stage1/libraries/base/Foreign/C.p_hi
* _build/stage1/libraries/base/Foreign/C.p_o _build/stage1/libraries/base/Foreign/C.p_hi
* _build/stage1/libraries/base/Foreign/C/Types.p_hi
* _build/stage1/libraries/base/Foreign/C/Types.p_o _build/stage1/libraries/base/Foreign/C/Types.p_hi
* _build/stage1/libraries/base/Foreign/Storable.p_hi
* _build/stage1/libraries/base/Foreign/Storable.p_o _build/stage1/libraries/base/Foreign/Storable.p_hi
* _build/stage1/libraries/base/GHC/Int.p_hi
* _build/stage1/libraries/base/GHC/Int.p_o _build/stage1/libraries/base/GHC/Int.p_hi
* _build/stage1/libraries/base/GHC/Arr.p_hi
* _build/stage1/libraries/base/GHC/Arr.p_o _build/stage1/libraries/base/GHC/Arr.p_hi
* _build/stage1/libraries/base/GHC/List.p_hi
* _build/stage1/libraries/base/GHC/List.p_o _build/stage1/libraries/base/GHC/List.p_hi
* _build/stage1/libraries/integer-gmp/GHC/Integer.p_hi
* _build/stage1/libraries/integer-gmp/GHC/Integer.p_o _build/stage1/libraries/integer-gmp/GHC/Integer.p_hi
* _build/stage1/libraries/integer-gmp/GHC/Integer/Type.p_hi
* _build/stage1/libraries/integer-gmp/GHC/Integer/Type.p_o _build/stage1/libraries/integer-gmp/GHC/Integer/Type.p_hi
* _build/stage1/libraries/ghc-prim/GHC/Classes.p_hi
* _build/stage1/libraries/ghc-prim/GHC/Classes.p_o _build/stage1/libraries/ghc-prim/GHC/Classes.p_hi
* OracleQ (ObjDepsKey ("_build/stage1/libraries/ghc-prim/.dependencies","_build/stage1/libraries/ghc-prim/GHC/Classes.p_o"))
* _build/stage1/libraries/ghc-prim/.dependencies
* _build/stage1/libraries/ghc-prim/autogen/GHC/Prim.hs
No generator for _build/stage1/libraries/ghc-prim/autogen/GHC/Prim.hs.

```

**Comment by snowleopard** [comment] 2016-11-08 08:37
@alexbiehl Thanks! I think this is related to this commit: https://github.com/snowleopard/hadrian/commit/eca7b6a6d9a17e44854cb8f696cec03140052208

Not sure what went wrong, the CI bots were happy. I'll have a look, but in the meanwhile feel free to rollback.

Was this a clean build?

**Comment by alexbiehl** [comment] 2016-11-08 08:40
Thanks for the fast response. 

Yes, it was (the trace you see was copied from a successive run after the error occurred first)

**Comment by snowleopard** [comment] 2016-11-08 12:59
Very strange. I cannot reproduce this either on my machine or by rerunning the CI bots.

@alexbiehl Could you try again, please? Make sure you do `clean` build first, and just in case double-check that the `_build` directory is indeed removed by the `clean`.

**Comment by alexbiehl** [comment] 2016-11-08 13:00
I reverted eca7b6a and it worked. I will try again later with that commit in.

**Comment by snowleopard** [comment] 2016-11-17 00:41
@alexbiehl I was unable to reproduce this. I intend to close this, unless the issue is still relevant for you.

**Closed** 2016-11-17 20:30 UTC
