### ISSUE TITLE
CI failure: can't find include file rts/fs.h

### ISSUE THREAD

**Issue by izgzhen** [snowleopard/hadrian#554] opened 2018-04-03 09:55 UTC
```
| Copy file (untracked): _build/stage1/libffi/build/inst/lib/libffi.a => _build/stage1/rts/build/libCffi_thr_l.a
| Successfully built custom library 'libffi'
Installing library in /home/travis/build/snowleopard/hadrian/ghc/_build/stage1/lib/../lib/x86_64-linux-ghc-8.5.20180402/rts-1.0
hadrian: can't find include file rts/fs.h
shakeArgsWith     0.000s    0%                           
Function shake   14.669s    1%                           
Database read     0.000s    0%                           
With database     0.001s    0%                           
Running rules  1314.416s   98%  ======================== 
Total          1329.086s  100%                           
Error when running Shake build system:
* _build/stage1/lib/package.conf.d/rts-1.0.conf
ExitFailure 1
```

https://travis-ci.org/snowleopard/hadrian/jobs/361477751

https://travis-ci.org/snowleopard/hadrian/jobs/361477747

please leave a word if you are looking into this bug, thanks!

**Comment by snowleopard** [comment] 2018-04-03 13:15
I haven't yet looked at this but I have a feeling that this is caused by a missing dependency on `fs.h`. 

These files are copied since #533.

Also, this code may be relevant: 

https://github.com/snowleopard/hadrian/blob/3a68f11c9d6ceebdb09f85804143dd2f1d49a502/src/Rules/Compile.hs#L38-L58

Or not :)

**Comment by izgzhen** [comment] 2018-04-07 09:30
HACK: `mkdir rts/rts; cp rts/fs* rts/rts`

**Comment by izgzhen** [comment] 2018-04-07 09:39
failed with another (probably unrelated) bug: https://github.com/snowleopard/hadrian/issues/559

**Comment by izgzhen** [comment] 2018-04-07 09:41
@Mistuke @snowleopard any idea on how to understand the HACK and fit it in our code?

**Comment by Mistuke** [comment] 2018-04-07 10:49
I don't quite understand why those includes are treated differently than the others. They're copied in tree way before any dependency analysis is done. But we probably don't need to install them anyway. Try in the GHC checkout removing `https://github.com/ghc/ghc/blob/master/rts/rts.cabal.in#L132` and the next line.

Note that it's not the building that fails, it's the package installing phase.

I don't have a Linux machine handy atm. but if you can't modify the tree easily I'll go set up a vm.

**Comment by snowleopard** [comment] 2018-04-07 14:55
I am with @Mistuke here: I don't quite understand why `fs` headers are causing issues.

But I'm getting more convinced that I'm right in suspecting that `needDependencies` is key here. These headers are different from others because they are generated and `needDependencies` might be unable to discover them. 

I'll try to have a look at this issue tonight.

**Comment by izgzhen** [comment] 2018-04-08 12:49
@Mistuke 

> Try in the GHC checkout removing https://github.com/ghc/ghc/blob/master/rts/rts.cabal.in#L132 and the next line.

I tried and it worked.

**Comment by snowleopard** [comment] 2018-04-12 01:35
I've added a workaround to fix the `fs*.h` issue: #566:

```haskell
    -- TODO: Get rid of this workaround.
    -- See https://github.com/snowleopard/hadrian/issues/554
    root -/- buildDir rtsContext -/- "rts/fs.h"     <~ return "rts"
    root -/- buildDir rtsContext -/- "rts/fs_rts.h" <~ return "rts"
```

The right way to fix this could be to add `fs*.h` files to `includes/rts` which is scanned by Cabal `copy`.

@izgzhen @Mistuke What do you think? 

In the meanwhile, the current workaround works, so I'm lowering the priority of this issue.

**Comment by izgzhen** [comment] 2018-04-12 02:02
looks good!

**Comment by Mistuke** [comment] 2018-04-12 02:08
Yes that's good, though looking at it again. I probably don't care about
having these installed. As the user can't use them easily anyway since they
need to know the right name space. I will commit a change removing these
from install once I get home.

Sorry for the extra work.

**Comment by Mistuke** [comment] 2018-04-12 03:09
Commit 111556f9e809962a91666c99d96cf80db361ee32 removes these files from `install-includes`

**Comment by Mistuke** [comment] 2018-04-12 06:54
Actually I've had to revert this, now I remember why they were there to begin with. The reach-ability analysis forces them to be. Because they're reachable from an exported header. This is all very annoying.

The exported headers are not useful. In fact you can't even call them so moving them to `include` would be a mistake I think. I think I know a fix that would work both for the testsuite and make/hadrian. I'll whip it up after work today.

**Comment by Mistuke** [comment] 2018-04-12 20:04
*sigh* well that's annoying. the CI failure was unrelated. I put up https://phabricator.haskell.org/D4591 for review to run it through the mac osx builder. if it's green I'll push the removal again.

Sorry for the delay.

**Comment by Mistuke** [comment] 2018-04-12 20:44
https://github.com/ghc/ghc/commit/5417c68977db2f2c2c1ce3b8b19ac1f540df471c done. the CI was clean so the failure was unrelated. You should be able to remove the work-around @snowleopard

**Comment by snowleopard** [comment] 2018-04-12 21:50
@Mistuke Great! I'll remove my workaround and will close this today.

**Comment by snowleopard** [comment] 2018-04-13 00:35
Done in the above commit. I think we can close this now.

**Closed by snowleopard** 2018-04-13 00:35 UTC
Labels: bug, medium-priority
