### ISSUE TITLE
Add more targets to Hadrian

### ISSUE THREAD

**Issue by chitrak7** [snowleopard/hadrian#536] opened 2018-03-25 22:04 UTC
Make currently supports a few targets which I couldn't find in Hadrian. Implementation of a few are pretty simple I think they are "help", "distclean", "maintainer-clean", "fasttest", "slowtest" @snowleopard

**Comment by izgzhen** [comment] 2018-03-26 02:04
ping https://github.com/snowleopard/hadrian/issues/360

**Comment by snowleopard** [comment] 2018-03-27 01:31
I agree, this seems like a duplicate of #360, so closing this. Let's revise/add more details to #360.

**Closed by snowleopard** 2018-03-27 01:31 UTC
