### ISSUE TITLE
Do not check src/Settings/User.hs into the repository

### ISSUE THREAD

**Issue by thomie** [snowleopard/hadrian#247] opened 2016-05-10 23:50 UTC
Any changes a user of Hadrian makes to that file should not get included into their GHC commits (by accident).

Possible solution:
* `git mv src/Settings/User.hs src/Settings/DefaultUser.hs` 
* In `build.sh`, if `src/Settings/User.hs` is missing, either abort or show a warning and `cp src/Settings/DefaultUser.hs src/Settings/User.hs`.

Checking out old revisions of Hadrian will cause some problems though.

**Comment by Ericson2314** [comment] 2016-05-10 23:53
A file can be committed and also `.gitignored`, in which case I believe `git add -u`, `git add /path/to/repo`, etc, will not pick up any change to it.

**Comment by snowleopard** [comment] 2016-05-11 00:11
I think @bgamari has already suggested the `.gitignore` solution mentioned by @Ericson2314. I like it. If I ever need to actually commit to `src/Settings/User.hs` I will find a way to do that (e.g. simply via the GitHub web interface).

For now I am keeping `src/Settings/User.hs` outside of `.gitignore` because I change it pretty frequently. But if it is annoying let's `.gitignore` it.

Thoughts?

**Comment by Ericson2314** [comment] 2016-05-11 01:21
`git add -f src/Settings/User.hs` would still work.

**Comment by thomie** [comment] 2016-05-11 01:27
Actually, both solutions have problems. 

An update to `src/Settings/DefaultUser.hs` (or `src/Settings/User.hs`) in master, can cause, when

* keeping `User.hs` outside repository: build failure
* adding `User.hs` to .gitignore: merge conflict

Both will cause spj to send a confused email to ghc-devs.

Compare this to the current situation, where adding some new setting to `mk/build.mk.sample` does not cause any problems for a user with an existing `mk/build.mk` file.

Not urgent to come up with a better solution. Adding to `.gitignore` is fine for now.

**Comment by ndmitchell** [comment] 2016-05-11 06:38
My suggestion is to use include paths. Have User.hs.sample in the ideal place for user settings, and a separate empty user settings file somewhere nice and obscure. Put the User.hs.sample path first on the include path so we pick it up if it exists but use empty settings of they don't.

**Comment by snowleopard** [comment] 2016-05-11 12:44
@ndmitchell Sorry I don't quite follow. Could you elaborate?

This is how I understood your comment.

We have two files:
* `hadrian/src/Settings/User.hs` just as we have currently. It is **not** in `.gitignore`.
* Initially missing file, e.g. `hadrian/UserSettings.hs`, which a user can create by copying `src/Settings/User.hs` and editing it as desired. This file **is** in `.gitignore`.

When compiling Hadrian we somehow play with include paths, so that `hadrian/UserSettings.hs` takes precedence if it exists. 

Is this roughly what you suggest? This sounds more complicated than the previous (`src/Settings/User.hs` is in `.gitignore`) solution, but will probably help to avoid the problems mentioned by @thomie. I also like the fact that user-defined settings can live outside `src` in this way, just in the Hadrian root.

**Comment by ndmitchell** [comment] 2016-05-11 12:48
I'd have `hadrian/UserSettings.hs.sample` and `hadrian/src/UserSettings.hs`. Users would create `hadrian/UserSettings.hs` which is picked up by the include path if present and is in `.gitignore`. I don't think it's very complicated (just one extra `-I` flag), and it does solve all the issues.

**Comment by snowleopard** [comment] 2016-05-11 12:53
Thanks, I see! So initially we have `hadrian/UserSettings.hs.sample == hadrian/src/UserSettings.hs`?

Is it important to use `hadrian/src/UserSettings.hs` instead of the current `hadrian/src/Settings/User.hs`?

**Comment by ndmitchell** [comment] 2016-05-11 12:57
They must both have the same module name, so yes, they can't be equivalent.

I would initially have `hadrian/src/UserSettings.hs` say "don't edit this, see `hadrian/UserSettings.hs`" and have it be complete but empty - e.g. `userSettings = mempty`, in contrast to `hadrian/UserSettings.hs` which would have lots of commented-out/`when False` code to do lots of interesting/relevant things.

**Comment by snowleopard** [comment] 2016-05-11 13:03
@ndmitchell Right, thanks, this makes sense, although I'm still unclear on some details. You seem to have a much clearer idea on how this will work -- could you perhaps put this into a PR?

**Comment by KaiHa** [comment] 2016-05-28 16:41
Hi, I believe I have implemented the discussed approach (see https://github.com/KaiHa/hadrian/commit/a53edf19c21a7cd289eee3f3de65ea23e27f111a). At least in my implementation there is the problem that hadrian is not recompiled by cabal if the file with the user settings is newly added. Does anyone have an idea what I did wrong or how It could be improved?

**Comment by snowleopard** [comment] 2016-05-29 09:58
Many thanks @KaiHa! Good that you've spotted the issue that Cabal doesn't detect the newly added settings file. @ndmitchell Have you got an idea how to workaround this?

**Comment by ndmitchell** [comment] 2016-05-30 05:59
Thanks @KaiHa! Unfortunately there's a bug in GHC that it depends on the CPP files included, not the non-existence of files earlier in the include path. This is a bug with CPP include paths, but the bug does not happen for Haskell include paths, so you need to avoid CPP and do the same include path trick but switching on which Haskell file is first in the include path.

**Comment by ndmitchell** [comment] 2016-05-30 06:11
I created https://ghc.haskell.org/trac/ghc/ticket/12135 with a small reproduceable ticket. It's a bug in GHC, not Cabal.

**Comment by KaiHa** [comment] 2016-05-30 06:40
Just to make sure I understood right, @ndmitchell you mean by adding `.` before `src` to the `hs-source-dirs` in the cabal file?

**Comment by ndmitchell** [comment] 2016-05-30 06:41
@KaiHa, yes, that's what I'd expect.

**Comment by KaiHa** [comment] 2016-05-30 07:28
OK, I have amended my changeset (see https://github.com/KaiHa/hadrian/commit/123bdb37674bfe60509886ec92c99e80b0588966). I tried to touch as few files as possible. This time the newly added file is recognized.

**Comment by snowleopard** [comment] 2016-05-30 08:23
@KaiHa @ndmitchell Thank you!

@KaiHa Could you raise a PR with your changes?

**Closed** 2016-05-31 06:10 UTC
Labels: enhancement
