### ISSUE TITLE
Windows build failure

### ISSUE THREAD

**Issue by ndmitchell** [snowleopard/hadrian#238] opened 2016-05-05 17:49 UTC
```
* _build/stage1/libraries/integer-gmp/libHSinteger-gmp-1.0.0.1.a
user error (Development.Shake.cmd, system command failed
Command: C:/Neil/ghc/noconf/ghc/inplace/mingw/bin/ar q _build/stage1/libraries/integer-gmp/libHSinteger-gmp-1.0.0.1.a @C:\Users\ndmit_000\AppData\Local\Programs\stack\i386-windows\msys2-20150512\tmp\extra-file-1943304748-9961491
Exit code: 1
Stderr:
C:/Neil/ghc/noconf/ghc/inplace/mingw/bin/ar: creating _build/stage1/libraries/integer-gmp/libHSinteger-gmp-1.0.0.1.a
C:/Neil/ghc/noconf/ghc/inplace/mingw/bin/ar: unable to rename '_build/stage1/libraries/integer-gmp/libHSinteger-gmp-1.0.0.1.a'; reason: Permission denied
```

With Hadrian on e61bd4021b696a17c72c8d259adf55621f9c3959.

**Comment by ndmitchell** [comment] 2016-05-05 19:11
I tried continuing and it worked. Perhaps a non-deterministic bug?

**Comment by snowleopard** [comment] 2016-05-05 19:12
Aha, here it is! #203. I looks like we couldn't reproduce it and eventually closed the issue.

**Comment by snowleopard** [comment] 2016-05-05 19:25
@ndmitchell Given that we eventually gave up on #203, what shall we do now? Merge this with #203? Keep it open or closed?

**Comment by ndmitchell** [comment] 2016-05-06 13:31
I don't have a good answer. The build is clearly broken in some non-deterministic interleaving. It hasn't been fixed, since it happened yesterday with no major changes since. But the chances of us reproducing are limited. :disappointed:

Note that compared on #203 this says "Permission denied" and not "No such file or directory". I had got RTS errors in the past, so this might indeed be a different bug.

**Comment by snowleopard** [comment] 2016-05-06 22:35
> Note that compared on #203 this says "Permission denied" and not "No such file or directory".

@ndmitchell Indeed, I didn't spot the difference.

The error still doesn't make sense to me: why does `ar` try to rename the archive? And then why does the rename fail? No one can possibly lock the archive that it is constructing.

**Comment by snowleopard** [comment] 2016-05-23 21:01
@ndmitchell What if I simply stop using temporary files here? There is only occurrence of `withTempFile` and two occurrences of `withTempDir` in Hadrian, so I could manually create files/directories myself.

**Comment by snowleopard** [comment] 2016-05-23 21:02
(We don't know for sure whether temporary files are to blame, but somehow I suspect they are.)

**Comment by ndmitchell** [comment] 2016-05-24 05:00
Having stress tested temp directories and files, I believe them to work. I don't see how a temp issue what cause problems at the renaming step?

**Comment by snowleopard** [comment] 2016-05-24 11:08
OK, let me list all possible interactions that may theoretically affect `ar`. I'm using check boxes to indicate items that I think are **not** responsible for the failure:
- [x] Before we run `ar` we `removeFile` the old `.a` archive, because we are using `ar` in the _quick append_ mode by passing flag `q`. Although we could in principle avoid this step, I don't see how it can possibly lead to the failure discussed in this issue.
- [x] One of `ar` arguments is a temporary file. @ndmitchell says this should be fine, hence the check mark. I came across some forum threads discussing failures associated with wrong file permissions, which makes me suspicious that temporary files could be somehow involved.
- [ ] If we are missing dependencies somewhere in the build system, and one of the rules attempts to use the `.a` file, while this rule is busy updating the archive, then we could probably cause this failure.


So, the last item seems to be the only suspect for now. @ndmitchell Have you got anything else?

Note that I have recently fixed some missing dependencies as part of #240.

**Comment by ndmitchell** [comment] 2016-05-24 20:57
@snowleopard - can you point me at the `removeFile`? And I'm assuming `arCmd` is where `ar` gets invoked?

**Comment by ndmitchell** [comment] 2016-05-24 21:18
I doubt it has anything to do with the temp file - the error revolves around the output filename. If the temp file was involved you'd expect to see it in the error message. I tried and failed to find the source to mingw ar, so I could see in what circumstances it wrote out that error, whether it was renaming from/to etc.

**Comment by snowleopard** [comment] 2016-05-24 21:32
@ndmitchell Here is where `removeFile` occurs, at the very start: https://github.com/snowleopard/hadrian/blob/master/src/Rules/Library.hs#L24

`arCmd` is actually a bit involved and could probably be improved, but here is the function that matters in our case: https://github.com/snowleopard/hadrian/blob/master/src/Settings/Builders/Ar.hs#L37-L40

**Comment by ndmitchell** [comment] 2016-05-24 21:48
Why not do the remove file in arCmd? The dislocation makes it way harder to reason about.

**Comment by snowleopard** [comment] 2016-05-24 22:21
@ndmitchell the current version of `arCmd` is not clever enough to know how the output file is called, so it can't delete it (unless we do something fragile like `argList !! 2`). But I agree that currently it's hard to reason about -- the whole collection of code for handling `ar`, scattered across several files, is a big mess.

Let me think how to improve the whole thing...

**Comment by ndmitchell** [comment] 2016-05-26 19:57
This doesn't seem right. Can't we define our own virtual "ar" builder which takes arguments in a defined order that we specify and then we call "ar" ourself? If the delete and create aren't next to each other then that massively increases the chance they aren't being called in a pair, and that is the source of the failure.

**Comment by snowleopard** [comment] 2016-05-26 23:47
@ndmitchell Yep, I'll move the `removeFile` next to the `ar` command. (However, I don't think that it is the source of the problem now.)

**Comment by ndmitchell** [comment] 2016-05-31 05:42
Once all the code is in one place I can run a `replicateM_ 1000` loop on it, which will tell us if single-threaded `ar` can ever get wedged. Probably unlikely, but a useful data point to rule out.

**Comment by izgzhen** [comment] 2017-07-18 13:04
Does this still happened now? Looks like AppVeyor is always happy

**Comment by snowleopard** [comment] 2017-07-18 15:32
I haven't seen this happen for a while. However, let's keep this open until I at least address some of the points raised above, i.e. the `removeFile` being so far from the `ar` command. I'll try to do this soon.

**Comment by snowleopard** [comment] 2017-07-19 00:29
OK, done. Let me close this issue for now, because I haven't seen this failure for a long time.

**Closed by snowleopard** 2017-07-19 00:29 UTC
Labels: bug, Windows
