### ISSUE TITLE
Warning at the end of a build `*.o`: openFile: does not exist

### ISSUE THREAD

**Issue by izgzhen** [snowleopard/hadrian#355] opened 2017-07-08 14:47 UTC
I've encountered several times that after a `build` has finish, there would be (for example):

```
shakeArgsWith                     0.002s    0%                           
Function shake                    0.456s    0%                           
Database read                     0.532s    0%                           
With database                     0.050s    0%                           
Running rules                   170.559s   99%  ======================== 
Pool finished (1 threads, 1 max)  0.002s    0%                           
Lint checking                     0.079s    0%                           
Total                           171.680s  100%                           
hadrian: _build/stage1/compiler/LlvmCodeGen/Base.o: openFile: does not exist (No such file or directory)
```

And the weird thing is that this phenomenon happens intermittently (not persistent across every build), randomly (some `.o`), and innocent (checking the `*.o` will show that it is indeed built, and if you run `build` again, that last line will be gone).

**Comment by snowleopard** [comment] 2017-07-08 17:49
I believe this is a duplicate of #291.

Seems to be a Shake bug, which I reported here: https://github.com/ndmitchell/shake/issues/496.

**Closed by snowleopard** 2017-07-08 17:49 UTC
