### ISSUE TITLE
DYNAMIC_BY_DEFAULT on different platforms

### ISSUE THREAD

**Issue by izgzhen** [snowleopard/hadrian#408] opened 2017-08-31 17:03 UTC
https://github.com/ghc/ghc/blob/c0feee90118333dac817cfad6f2dedc0a886d1bd/mk/config.mk.in#L132-L142

**Comment by snowleopard** [comment] 2017-08-31 17:14
Not sure, but this may be part of #248?

**Comment by izgzhen** [comment] 2017-09-01 09:02
> Not sure, but this may be part of #248?

Probably ... but they've disabled it explicitly in `mk/config.mk` now anyway, so it is low-priority.

**Comment by snowleopard** [comment] 2018-04-24 10:57
I think we better close this one as a duplicate of #248.

**Closed by snowleopard** 2018-04-24 10:57 UTC
Labels: low-priority
