### ISSUE TITLE
Error in Shake OracleQ parsing (spaces in file names?)

### ISSUE THREAD

**Issue by istandleet** [snowleopard/hadrian#287] opened 2016-09-05 18:21 UTC
It looks like the handling for spaces in file names is improper.

Original and rerun results:
```
shakeArgsWith    0.000s    0%
Function shake   0.196s    0%
Database read    0.001s    0%
With database    0.000s    0%
Running rules  219.539s   99%  =========================
Total          219.736s  100%
Error when running Shake build system:
* OracleQ (ConfigKey "host-os")
("parse failed when parsing binding","Files/Haskell\nPlatform/7.10.2-a/lib/extralibs/bin/HsColour\nld             = C:/hask/ghc/inplace/ming")


C:\hask\ghc\hadrian>stack exec hadrian -- --directory ".." -j --flavour=quickest
shakeArgsWith   0.000s    0%
Function shake  0.174s   77%  =========================
Database read   0.000s    0%
With database   0.000s    0%
Running rules   0.051s   22%  =======
Total           0.225s  100%
Error when running Shake build system:
* OracleQ (ConfigKey "host-os")
("parse failed when parsing binding","Files/Haskell\nPlatform/7.10.2-a/lib/extralibs/bin/HsColour\nld             = C:/hask/ghc/inplace/ming")
```

**Comment by istandleet** [comment] 2016-09-05 18:22
I don't know how to build labels, but this is likely windows specific

**Comment by snowleopard** [comment] 2016-09-05 18:35
@istandleet Actually I think the problem is the `\n` symbol. This is strange. Can you attach your `system.config` file?

**Comment by snowleopard** [comment] 2016-09-05 18:38
Just to clarify: the value of the configuration setting should have been `Files/Haskell\nPlatform/7.10.2-a/lib/extralibs/bin/HsColour`, not `Files/Haskell\nPlatform/7.10.2-a/lib/extralibs/bin/HsColour\nld             = C:/hask/ghc/inplace/ming` as shown in the error message.

**Comment by snowleopard** [comment] 2016-09-05 18:40
I'm confused. The value of the configuration setting `Files/Haskell\nPlatform/7.10.2-a/lib/extralibs/bin/HsColour\nld             = C:/hask/ghc/inplace/ming` doesn't make much sense. It looks as if the configuration file has been corrupted?

**Comment by istandleet** [comment] 2016-09-05 18:40
sorry - where should I find that guy?

**Comment by snowleopard** [comment] 2016-09-05 18:40
Ah, sorry. It's in `hadrian/cfg/system.config`.

**Comment by istandleet** [comment] 2016-09-05 18:42
[system.config.txt](https://github.com/snowleopard/hadrian/files/455514/system.config.txt)
Changed to .txt for upload

**Comment by istandleet** [comment] 2016-09-05 18:44
I meant, shouldn't the setting be `Files/Haskell%20Platform/7.10.2-a/lib/extralibs/bin/HsColour`?

**Comment by istandleet** [comment] 2016-09-05 18:57
This actually may be my doing - I set up git to download "as is", so it may be expecting `/r/n` as line delimiters and therefore expect to be able to use `/n` as a delimiter. I can reinstall git to test later tonight

**Comment by snowleopard** [comment] 2016-09-05 18:58
@istandleet You are right about spaces. Just for the record, here is the problematic fragment:
```
hscolour       = C:/Program
Files/Haskell
Platform/7.10.2-a/lib/extralibs/bin/HsColour
```
This is produced by GHC's `configure` script, which is not part of Hadrian... 

Actually changing `git` settings might help -- give it a try.

Otherwise you could try the following to see whether this is the only issue:
* Manually edit the `system.config` file to have spaces ` ` instead of `\n` in the `hscolour` path.
* Run Hadrian with flag `--skip-configure`.

**Comment by istandleet** [comment] 2016-09-05 19:04
The manual solution with `--skip-configure` worked :)

**Comment by snowleopard** [comment] 2016-09-05 22:07
@istandleet Awesome! :)

I hope the `git` could also do the trick for you -- please let me know if it works. If not, there is another possible solution that does not require passing the `--skip-configure` flag (editing `UserSettings.hs` file).

**Comment by snowleopard** [comment] 2016-09-06 18:06
@istandleet Any updates on trying another CRLF mode in `git`? If it works I guess we can close this issue and add a note to the README.

**Closed** 2016-09-13 18:04 UTC
Labels: Windows
