### ISSUE TITLE
Unknown command HOST

### ISSUE THREAD

**Issue by alexbiehl** [snowleopard/hadrian#261] opened 2016-06-07 10:32 UTC
I am trying to compile ghc on a Windows 7 machine. So far `ghc-stage1` built fine. But compiling `libffi` fails with  `Command "HOST" not found` (roughly translated as for some reason the shell spits out german errors). 

I invoke hadrian using stack with the command line from the tutorial: 
`stack exec --stack-yaml=hadrian/stack.yaml -- hadrian/build.bat -j --flavour=quick`

I manually unpacked `libffi-3.2.1.tar` tarball and tried `stack exec ./configure` and `stack exec make` and it built just fine. 

As I know it `HOST` denotes an environment variable and not a command. So maybe something is incorrectly substituted? Im afraid I don't know anything about `autoconf` and `make`.

Attached is the hadrian output for libffi: 
````
/--------------------------------------------------------------------\
| Run Make "_build/stage1/libffi" (stage = Stage1, package = libffi) |
|      input: none                                                   |
|  => output: none                                                   |
\--------------------------------------------------------------------/
gmake.exe: Entering directory `C:/Users/abiehl/git/ghc/_build/stage1/libffi'
Makefile:2727: warning: overriding recipe for target `tags'
Makefile:2716: warning: ignoring old recipe for target `tags'
Makefile:2762: warning: overriding recipe for target `ctags'
Makefile:2750: warning: ignoring old recipe for target `ctags'
Der Befehl "HOST" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
gmake.exe: *** [install] Error 1
gmake.exe: Leaving directory `C:/Users/abiehl/git/ghc/_build/stage1/libffi'
shakeArgsWith    0.000s    0%
Function shake   0.176s    0%
Database read    0.447s    0%
With database    0.010s    0%
Running rules  154.078s   99%  =========================
Total          154.710s   99%
Error when running Shake build system:
* OracleQ (PackageDataKey ("_build/stage1/rts/package-data.mk","_build_stage1_rts_COMPONENT_ID"))
* _build/stage1/rts/package-data.mk
* _build/stage1/rts/ffi.h
* _build/stage1/rts/ffi.h _build/stage1/rts/ffitarget.h
user error (Development.Shake.cmd, system command failed
Command: cmd.exe /d/q/c C:\Temp\extra-dir-594045904475\s.bat
Exit code: 2
Stderr:
Makefile:2727: warning: overriding recipe for target `tags'
Makefile:2716: warning: ignoring old recipe for target `tags'
Makefile:2762: warning: overriding recipe for target `ctags'
Makefile:2750: warning: ignoring old recipe for target `ctags'
Der Befehl "HOST" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
gmake.exe: *** [install] Error 1
)
````

**Comment by snowleopard** [comment] 2016-06-07 21:48
@alexbiehl Can you run Make manually in `_build/stage1/libffi`? Looks like on your system Make is called `gmake`, so what happens if you run:
```bash
cd _build/stage1/libffi
gmake install
```
If this fails, perhaps you can also try `make` instead of `gmake`. (Looks like this is what you tried via Stack already, but without the `install` argument).

Note, Hadrian uses `gmake` because this is what the `configure` script tells it to use. To double-check this, have a look at the `hadrian/cfg/system.config` file produced by `configure` -- what path does it provide for `make`?

**Comment by alexbiehl** [comment] 2016-06-08 08:09
Hello Andrey,

Looking into `hadrian/cfg/system.config` indeed gives `make = gmake`.

Trying your suggestion results in the mentioned error. Trying `cd
_build/stage1/libffi && stack exec make install` works as expected.

I am wondering since I execute the build using `stack exec ...` why it
doesn't pick `make` from stack?


Andrey Mokhov <notifications@github.com> schrieb am Di., 7. Juni 2016 um
23:48 Uhr:

**Comment by snowleopard** [comment] 2016-06-08 08:47
@alexbiehl Hadrian doesn't pick which Make to use. This is decided by `configure` (I personally don't like this two layer architecture and find it confusing, but that's how things currently are in GHC; see #227).

The easiest fix for you is to edit `system.config.in` replacing `@MakeCmd@` with `make`, hence picking the right Make manually. A more long-term solution is to investigate why `configure` is picking `gmake` and perhaps fix this in GHC.

**Comment by alexbiehl** [comment] 2016-06-08 09:05
That did it! Thank you!

Andrey Mokhov <notifications@github.com> schrieb am Mi., 8. Juni 2016 um
10:47 Uhr:

**Comment by snowleopard** [comment] 2016-06-08 09:35
@alexbiehl Great!

@hvr Do I understand correctly that the recommended way of solving this problem is to add `--with-make=` flag to `configure` so that users can manually pick which Make to use if they like? If we had this feature then the right solution to this issue in Hadrian would be to edit `UserSettings.hs` like this:
```haskell
-- | Modify default build command line arguments.
userArgs :: Args
userArgs = builder (Configure ".") ? arg "--with-make=make"
```
This has advantages, because it's tracked (Hadrian reruns all affected rules) and the users don't have to touch `system.config.in` file.

**Comment by hvr** [comment] 2016-06-08 10:48
@snowleopard The `make` command is special as it's one of the few things that are not configured by `./configure` in Autoconf's model. The user is in charge to call the proper `make` implementation, and this choice is then recursively passed on via a `MAKE`-variable, c.f. https://www.gnu.org/software/make/manual/html_node/MAKE-Variable.html

So even if you were to configure a `make` implementation to use, the use still would have to call `make`, and you only risk conflicting information between of what `configure` probed, and what the user really invoked.

That's why makes no sense to tell `configure`, and the proper way to detect that somebody is using the wrong `make` implementation is to add a check directly in the Makefiles which require e.g. GNU make semantics.

**Comment by thomie** [comment] 2016-06-08 12:43
alexbiehl: can you run the following two commands please:
* `gmake --version`
* `make --version`

If `gmake` exists, it should work. If it doesn't, it would be good to know why not.

**Comment by alexbiehl** [comment] 2016-06-08 13:39
I ran the commands:

````
$ gmake --version
GNU Make 3.81.90
Built for x86_64-w64-mingw32
Copyright (C) 2009  Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html
>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
````

````
$ make --version
GNU Make 4.1
Built for x86_64-pc-msys
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html
>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
````


Thomas Miedema <notifications@github.com> schrieb am Mi., 8. Juni 2016 um
14:43 Uhr:

**Comment by thomie** [comment] 2016-06-08 17:07
Thanks. GNU Make 3.81 was released in 2006.

configure.ac currently contains:
```
# We got caught by
#     http://savannah.gnu.org/bugs/index.php?1516
#     $(eval ...) inside conditionals causes errors
# with make 3.80, so warn the user if it looks like they're about to
# try to use it.
# We would use "grep -q" here, but Solaris's grep doesn't support it.
print_make_warning=""
checkMake380() {
    make_ver=`$1 --version 2>&1 | head -1`
    if echo "$make_ver" | grep 'GNU Make 3\.80' > /dev/null
    then
        print_make_warning="true"
    fi
    if echo "$make_ver" | grep 'GNU Make' > /dev/null
    then
        MakeCmd=$1
        AC_SUBST(MakeCmd)
    fi
}

checkMake380 make
checkMake380 gmake
```

So 3.80 is known to be buggy, but what about 3.81?
@kgardas: which version of make or you using? Maybe we should just increase the lower bound to 3.82 or even higher?

**Comment by snowleopard** [comment] 2016-06-08 22:55
> That's why it makes no sense to tell `configure` (nor for `configure` to pick any `make`)

@hvr Well, that's what we have already, see the above comment by @thomie.

I fail to see why we should treat Make differently from other builders: Hadrian occasionally runs Make to build stuff. Like GMP or Libffi. Make is just another builder! So if `configure` is our magic solution to probing and picking right builders, why not use it in this case too?

(But then if _you_ tell me _not_ to use `configure` then I certanly won't fight over this ;-) I'll happily let people make the choice in Hadrian.)

**Comment by hvr** [comment] 2016-06-09 08:17
@snowleopard well, @thomie pointing out that `configure` is doing it now doesn't invalidate my argument; it's still wrong for `configure` to check for `make` properties since `configure` does not control which `make` implementation the user will call afterwards.

Maybe it's unclear what I mean; here's what will go wrong:

```
# first we configure with the "good" make executable 
$ ./configure --with-make=/opt/freeware/bin/gmake
# but then the user, or the tooling which is unaware of this choice does, calls a different `make` executable
$ make all
# ...and now whatever `configure` assumed about the `gmake` is no longer valid for `make`
```

**Comment by thomie** [comment] 2016-06-09 08:43
@hvr 

I doubt it matters which version of `make` is used for the toplevel Makefile (which doesn't even exist yet, so your point, if valid, should be very low on any priorities list). That toplevel Makefile shouldn't do anything fancy at all.

But Hadrian also needs the call `make` for `libffi` and `libgmp`, and there the version does matter (and can be different from the one the user called the toplevel Makefile with) as evidenced by this ticket.

I agree with @snowleopard:
> I fail to see why we should treat Make differently from other builders: Hadrian occasionally runs Make to build stuff. Like GMP or Libffi. Make is just another builder!

**Comment by snowleopard** [comment] 2016-10-15 23:14
Closing this, as the issue isn't really in Hadrian, but in the GHC's `configure` script.

**Closed by snowleopard** 2016-10-15 23:14 UTC
