### ISSUE TITLE
Build failure: ././tools/derive: getDirectoryContents:openDirStream: does not exist 

### ISSUE THREAD

**Issue by snowleopard** [snowleopard/hadrian#634] opened 2018-06-22 22:03 UTC
We are currently seeing build failures on all CI bots:
```
././tools/derive: getDirectoryContents:openDirStream: does not exist (No such file or directory)

Error when running Shake build system:
* _build/stage1/lib/bin/unlit
* OracleQ (PackageDataFile (Context {stage = Stage1, package = Package {pkgLanguage = Haskell, pkgType = Program, pkgName = "unlit", pkgPath = "utils/unlit"}, way = v}))
* _build/stage1/utils/unlit/setup-config
* _build/stage0/bin/ghc
* OracleQ (PackageDataFile (Context {stage = Stage0, package = Package {pkgLanguage = Haskell, pkgType = Program, pkgName = "ghc-bin", pkgPath = "ghc"}, way = v}))
* _build/stage0/ghc/setup-config
* _build/stage0/lib/package.conf.d/ghc-boot-8.7.conf
* OracleQ (PackageDataFile (Context {stage = Stage0, package = Package {pkgLanguage = Haskell, pkgType = Library, pkgName = "ghc-boot", pkgPath = "libraries/ghc-boot"}, way = v}))
* _build/stage0/libraries/ghc-boot/setup-config
* _build/stage0/lib/package.conf.d/binary-0.8.5.1.conf
* OracleQ (PackageDataFile (Context {stage = Stage0, package = Package {pkgLanguage = Haskell, pkgType = Library, pkgName = "binary", pkgPath = "libraries/binary"}, way = v}))

* _build/stage0/libraries/binary/setup-config
ExitFailure 1
```

**Comment by snowleopard** [comment] 2018-06-22 22:32
@alpmestan Thanks! Yes, I've also been wondering if these commits are to blame. I'll try to find a fix during the weekend.

**Comment by chitrak7** [comment] 2018-06-23 08:43
I think this is because ghc is migrating to 8.6. Even the default make build is failing in my system. Maybe we should just wait for a while.

**Comment by chitrak7** [comment] 2018-06-23 08:45
Even the make build is failing. I think its just because of some changes in ghc and nothing to do with hadrian.

**Comment by snowleopard** [comment] 2018-06-23 10:10
@chitrak7 Yes, I agree, let's wait for a couple of days.

**Comment by alpmestan** [comment] 2018-06-23 11:09
It's a bit odd. Last night `./validate --slow` run on Circle CI was green: https://circleci.com/gh/ghc/ghc/6389

But I have indeed seen the issue from the first comment when using hadrian yesterday.

I tried building the commit `33724fc754 Remove -Wamp flag` (tip of master when I started) with both, with the `quickest` flavour.

- Fails with hadrian, same error as in the first comment of this issue.
- Works with the make build system. I've built a complete stage2 compiler.

There does seem to be something odd going on _in hadrian_.

**Comment by snowleopard** [comment] 2018-06-23 11:23
@alpmestan I've also reproduced on my machine. The problem occurs when configuring the `binary` package, which contains the following in the Cabal file:
```
extra-source-files:
  README.md changelog.md docs/hcar/binary-Lb.tex tools/derive/*.hs
```
I'm not sure how GHC version changes could possibly be relevant...

**Comment by alpmestan** [comment] 2018-06-23 13:28
> I'm not sure how GHC version changes could possibly be relevant...

Well, have we bumped Cabal by chance? Maybe that introduced a problem. So basically, it's looking for this `libraries/binary/tools/derive/` directory, but at the wrong place? Any chance you can print the CWD when the configuring takes place?

**Comment by alpmestan** [comment] 2018-06-25 10:39
I can confirm the breakage got introduced in https://github.com/ghc/ghc/commit/c35ad6e0b3c62976e6251f1e9c47fe83ff15f4ce. I suspect it's the Cabal bump that's to blame. I'll try "un-bumping" it while keeping everything else the same.

**Comment by alpmestan** [comment] 2018-06-25 11:08
Here's the history of commits between pre-bump Cabal and post-bump Cabal:

```
8fbacca02 Bump upper bound on containers to <0.7
2e8a45f4a Introduce Distribution.Compat.Map.Lazy module
f2dd0ead6 Added note to the documentation of "mixins:"
96f9c1f43 Added documentation for Backpack-related fields.
283030c0b Re-target glob features to 2.4, rather than 3.0.
9796ec68a Musical chairs, part 1.5: more commands need warnings
e4294f319 Allow globs to match against a suffix of a file's extensions
d6e0edbe7 Make cabal check play nice with cabal-testsuite.
0ea56b5be bootstrap.sh: Bump HTTP version.
d4b89ecfe Update bootstrap.sh.
068119006 Allow time 1.9 as well.
48d2b3afc Allow network 2.7
93fee88f9 Haddock: Update package index for each component
4e0c701a2 Typo
3fd31d017 Bump '--since-qual' to Haddock 2.20
c4b235e8c fix test
ff1f6c836 Add a 'quickjump' option, implied by 'for-hackage'
442355096 Pass in 'since-qual' for new enough Haddock
02bfdfd93 Deprecate hscolour, add hyperlink-source synonyms
15e793aa4 Musical chairs, part 1: add warnings and aliases
fb67b25e1 Oops, there was already a changelog for new-clean. I'm stupid.
9b3d3157b Changelog for new-clean
157b4c259 Fix rebasing error in new-clean
e5f8dc3fe Add cabal new-clean (closes #2957)
b8c4ce3da Fix the test case some more.
```

**Comment by alpmestan** [comment] 2018-06-25 11:17
And indeed, if I build against b8c4ce3da, the pre-bump commit of Cabal, I don't get the error.

**Comment by snowleopard** [comment] 2018-06-25 11:18
@alpmestan Many thanks for digging into this. Perhaps we could bisect to the offending commit?

**Comment by alpmestan** [comment] 2018-06-25 11:18
Yes, looking into precisely this right now.

**Comment by snowleopard** [comment] 2018-06-25 11:51
@alpmestan Changing the Cabal file to avoid using the wildcard fixes the problem:
```
extra-source-files:
  README.md changelog.md docs/hcar/binary-Lb.tex tools/derive/BinaryDerive.hs tools/derive/Example.hs
```

Unfortunately, there other packages are broken too -- the next failure is with `hsc2hs` which has:
```
extra-source-files:
  changelog.md
  test/asm/*.s
```

**Comment by angerman** [comment] 2018-06-25 12:20
Aren’t we building hadrian against the same Cabal lib we build GHC with? I thought the cabal new-build script did that?

We should in any case make sure we build hadrian against lib:Cabal in the same version we build it into GHC.

I fear we will run into various issues again and again if we don’t.  GHc and lib:Cabal are developed in symbiosis and it happens time and again that ghc depends on features of lib:Cabal as specified as a submodule in GHC.

With the drop of `ghc-cabal` and using lib:Cabal directly, hadrian needs to use the same `lib:Cabal` Version as GHC to interface properly with the cabal files in GHCs development branch.

**Comment by alpmestan** [comment] 2018-06-25 14:08
hadrian is built against the in-tree `Cabal` from `./libraries/Cabal/` so presumably hadrian uses it all the time for all its Cabal needs. So you're saying this could be a problem when using the boot GHC to build stage 1? If not, then I don't understand what you're hinting at.

**Comment by angerman** [comment] 2018-06-25 14:54
Yes, that one should be good. I was just afraid we might somehow build hadrian against the lib:Cabal that the bootstrap compiler provides.

**Comment by alpmestan** [comment] 2018-06-25 16:30
It's the switch from

```
d6e0edbe7 Make cabal check play nice with cabal-testsuite.
```
to
```
e4294f319 Allow globs to match against a suffix of a file's extensions
```

that makes this error message appear for me. Before that second commit, the build fails further down the road, with a complain about an unsuitable version of containers (which make sense, my whole GHC tree but Cabal are set to that commit where Ben bumped it, but then with all those commits, I'm back to a Cabal that doesn't support that just yet).

This seems rather obviously related to the comments you made earlier today, @snowleopard :-)

**Comment by alpmestan** [comment] 2018-06-26 13:06
``` patch
diff --git a/src/Hadrian/Haskell/Cabal/Parse.hs b/src/Hadrian/Haskell/Cabal/Parse.hs
index 1f540351a0..fa68ce674a 100644
--- a/src/Hadrian/Haskell/Cabal/Parse.hs
+++ b/src/Hadrian/Haskell/Cabal/Parse.hs
@@ -37,6 +37,7 @@ import qualified Distribution.Types.LocalBuildInfo             as C
 import qualified Distribution.Text                             as C
 import qualified Distribution.Types.MungedPackageId            as C
 import qualified Distribution.Verbosity                        as C
+import System.Directory (withCurrentDirectory)
 
 import Base
 import Builder
@@ -156,7 +157,9 @@ configurePackage context@Context {..} = do
     argList     <- interpret (target context (GhcCabal Conf stage) [] []) flavourArgs
     verbosity   <- getVerbosity
     let v = if verbosity >= Loud then "-v3" else "-v0"
-    liftIO $ C.defaultMainWithHooksNoReadArgs hooks gpd
+    liftIO $ print (argList ++ ["--flags=" ++ unwords flagList, v])
+    liftIO . withCurrentDirectory (pkgPath package) $
+      C.defaultMainWithHooksNoReadArgs hooks gpd
         (argList ++ ["--flags=" ++ unwords flagList, v])
 
 -- | Copy the 'Package' of a given 'Context' into the package database
diff --git a/src/Settings/Builders/Common.hs b/src/Settings/Builders/Common.hs
index ae660db31e..6cceadebe2 100644
--- a/src/Settings/Builders/Common.hs
+++ b/src/Settings/Builders/Common.hs
@@ -60,9 +60,10 @@ packageDatabaseArgs = do
     stage <- getStage
     dbPath <- expr (packageDbPath stage)
     expr (need [dbPath -/- packageDbStamp])
+    top <- expr topDirectory
     root <- getBuildRoot
     prefix <- ifM (builder Ghc) (return "-package-db ") (return "--package-db=")
-    arg $ prefix ++ root -/- relativePackageDbPath stage
+    arg $ prefix ++ top -/- root -/- relativePackageDbPath stage
 
 bootPackageDatabaseArgs :: Args
 bootPackageDatabaseArgs = do
```

gets me a little further, but it looks like all of a sudden we just can't rely on Cabal to reliably figure out where to look for things when we're not calling it from the same directory where the .cabal file resides?

I end up with:

```
Configuring terminfo-0.4.1.1...
creating /home/alp/WT/ghc-hadrian/_baz/stage0/libraries/terminfo/build
[...]
Using Cabal-2.3.0.0 compiled by ghc-8.2
Using compiler: ghc-8.2.2
Using install prefix: ${pkgroot}/..
Executables installed in: ${pkgroot}/../bin
Libraries installed in:
${pkgroot}/../lib/x86_64-linux-ghc-8.2.2/terminfo-0.4.1.1
Dynamic Libraries installed in: ${pkgroot}/../lib/x86_64-linux-ghc-8.2.2
Private executables installed in:
${pkgroot}/../libexec/x86_64-linux-ghc-8.2.2/terminfo-0.4.1.1
Data files installed in:
${pkgroot}/../share/x86_64-linux-ghc-8.2.2/terminfo-0.4.1.1
Documentation installed in:
${pkgroot}/../share/doc/x86_64-linux-ghc-8.2.2/terminfo-0.4.1.1
Configuration files installed in: ${pkgroot}/../etc
Using alex version 3.2.4 given by user at:
/nix/store/8g2sphn5mmkzhc71h7s2si71r2j34fq9-ghc-build-environment/bin/alex
Using ar given by user at:
/nix/store/21ymadblbmsbb2bk4q7gl4kjasp8zmgd-binutils-2.30/bin/ar
No c2hs found
No cpphs found
No doctest found
Using gcc version 7.3.0 given by user at:
/nix/store/vhg71q6zx8xbb851kyah0flyjjglapq7-gcc-wrapper-7.3.0/bin/cc
Using ghc version 8.2.2 given by user at:
/nix/store/8g2sphn5mmkzhc71h7s2si71r2j34fq9-ghc-build-environment/bin/ghc
Using ghc-pkg version 8.2.2 given by user at:
/nix/store/8g2sphn5mmkzhc71h7s2si71r2j34fq9-ghc-build-environment/bin/ghc-pkg
No ghcjs found
No ghcjs-pkg found
No greencard found
Using haddock version 2.18.1 found on system at:
/nix/store/8g2sphn5mmkzhc71h7s2si71r2j34fq9-ghc-build-environment/bin/haddock
Using happy version 1.19.9 given by user at:
/nix/store/8g2sphn5mmkzhc71h7s2si71r2j34fq9-ghc-build-environment/bin/happy
Using haskell-suite found on system at: haskell-suite-dummy-location
Using haskell-suite-pkg found on system at: haskell-suite-pkg-dummy-location
No hmake found
Using hpc version 0.67 found on system at:
/nix/store/8g2sphn5mmkzhc71h7s2si71r2j34fq9-ghc-build-environment/bin/hpc
Using hsc2hs version 0.68.2 found on system at:
/nix/store/8g2sphn5mmkzhc71h7s2si71r2j34fq9-ghc-build-environment/bin/hsc2hs
No hscolour found
No jhc found
Using ld found on system at:
/nix/store/yj9p0rmq6phvg5x653zl9f138pm7cnzg-binutils-wrapper-2.30/bin/ld
No pkg-config found
Using runghc version 8.2.2 found on system at:
/nix/store/8g2sphn5mmkzhc71h7s2si71r2j34fq9-ghc-build-environment/bin/runghc
Using strip version 2.30 found on system at:
/nix/store/21ymadblbmsbb2bk4q7gl4kjasp8zmgd-binutils-2.30/bin/strip
Using tar found on system at:
/nix/store/fjh974kzdcab7yp0ibmwwymmgbi6cg59-gnutar-1.30/bin/tar
No uhc found
hadrian: configure script not found.
shakeArgsWith   0.000s    0%                           
Function shake  0.247s    0%                           
Database read   0.004s    0%                           
With database   0.000s    0%                           
Running rules  30.895s   99%  =========================
Total          31.146s  100%                           
Error when running Shake build system:
* _baz/stage1/lib/bin/unlit
* OracleQ (PackageDataFile (Context {stage = Stage1, package = Package {pkgLanguage = Haskell, pkgType = Program, pkgName = "unlit", pkgPath = "utils/unlit"}, way = v}))
* _baz/stage1/utils/unlit/setup-config
* _baz/stage0/bin/ghc
* OracleQ (PackageDataFile (Context {stage = Stage0, package = Package {pkgLanguage = Haskell, pkgType = Program, pkgName = "ghc-bin", pkgPath = "ghc"}, way = v}))
* _baz/stage0/ghc/setup-config
* _baz/stage0/lib/package.conf.d/ghc-8.6.0.20180620.conf
* OracleQ (PackageDataFile (Context {stage = Stage0, package = Package {pkgLanguage = Haskell, pkgType = Library, pkgName = "ghc", pkgPath = "compiler"}, way = v}))
* _baz/stage0/compiler/setup-config
* _baz/stage0/lib/package.conf.d/terminfo-0.4.1.1.conf
* OracleQ (PackageDataFile (Context {stage = Stage0, package = Package {pkgLanguage = Haskell, pkgType = Library, pkgName = "terminfo", pkgPath = "libraries/terminfo"}, way = v}))
* _baz/stage0/libraries/terminfo/setup-config
ExitFailure 1
```

Here, Cabal fails to find the `configure` script at the root of the terminfo directory, because I'm running it from the top of my ghc source tree. I'm not sure whether hadrian is doing something silly or whether that Cabal patch just reveals something that just feels wrong, namely that this code in Cabal [assumes we're running it from the cabal file's directory](https://github.com/haskell/cabal/blob/e4294f3196f7b810db601ffbaa02b6538620b4b4/Cabal/Distribution/Simple/Glob.hs#L196), apparently? Thoughts anyone? I'm really not a Cabal expert, so I'm really not sure what the proper fix should be here.

**Comment by snowleopard** [comment] 2018-06-26 14:46
@alpmestan I remember we had similar issues when initially trying to get rid of `ghc-cabal`, but then somehow @angerman managed to make everything work. 

Presumably, Make works because it still uses `ghc-cabal` which can change the current directory. I think we cannot do the same, since this would mess up the current directory of other parallel Shake threads.

**Comment by snowleopard** [comment] 2018-06-26 14:51
Sorry, I don't think I can offer anything more useful, since I also don't know how Cabal works and why it has suddenly stopped working well with Hadrian. Perhaps, @hvr can shed some light on this? Let me also CC @quasicomputational who made the commit https://github.com/haskell/cabal/commit/e4294f3196f7b810db601ffbaa02b6538620b4b4 which seems to be the issue.

**Comment by quasicomputational** [comment] 2018-06-26 15:32
Thanks for the ping. I managed to break Cabal's `master` for a few weeks that would cause a similar error, but this looks like a slightly different thing since `data-files` isn't involved (right?).

Would it be possible to run Cabal with `-vdebug` (or pass `debug` as the verbosity to whatever function is being called) and dump the output from just before the error? There should be an "Expanding glob:" line there.

The assumption in the Cabal code is that the CWD is the directory of the `.cabal` code, and it has been for a while. haskell/cabal#5284 was the first PR to touch the globbing code for a decade, and as you can see the behaviour wrt CWD is very similar. There's no inherent reason why that assumption can't be removed and code adjusted, AFAIK, except for the possibility of lurking bugs, but I'd imagine that most of those have already been flushed out by Hadrian.

I am surprised that this only started manifesting with that commit, unless Hadrian is calling `cabal check` or the moral equivalent somehow, in which case it makes perfect sense.

**Comment by quasicomputational** [comment] 2018-06-26 15:50
Aha. `checkPackageFiles` is called from `Distribution.Simple.Configure` with a `"."` argument. That would definitely fit with the evidence as the cause.

**Comment by snowleopard** [comment] 2018-06-26 15:59
@quasicomputational Many thanks for having a look so quickly! Do you think you can fix this in Cabal?

**Comment by quasicomputational** [comment] 2018-06-26 16:11
Looks like a simple fix (famous last words). I'll try to get it tested and prepare a PR today, and then I think you'll need GHCHQ to bump the Cabal submodule once that's merged, right?

**Comment by snowleopard** [comment] 2018-06-26 16:14
Thanks! Yes, that would be great. You can also test your fix locally by trying to build GHC with Hadrian -- happy to help with this.

**Comment by alpmestan** [comment] 2018-06-26 16:49
Same here. Thanks a lot @quasicomputational :-)

**Comment by quasicomputational** [comment] 2018-06-26 17:59
I've put up the PR and I'm in the process of verifying it works to fix Hadrian. That might overflow my time tonight and spill out into tomorrow, but feel free to try it out yourselves in the meantime.

**Comment by quasicomputational** [comment] 2018-06-26 18:14
OK, I checked that I can reproduce the `getDirectoryContents` error with GHC commit 3d002087dce9c61932dd17047902baa83581f4df and all submodules updated. Then I bumped Cabal to bf5a718a1a26231db6a14aa281a186d641700831, which is the PR's latest commit and so should be fixed, and now I am getting this error:

```
$ hadrian/build.sh
Up to date
Up to date
Warning: libraries/text/text.cabal:4:1: The field "bug-reports" is specified
more than once at positions 4:1, 42:1
Warning: libraries/haskeline/haskeline.cabal:4:1: The field "category" is
specified more than once at positions 4:1, 10:1
Warning: libraries/text/text.cabal:4:1: The field "bug-reports" is specified
more than once at positions 4:1, 42:1
Warning: utils/hpc/hpc-bin.cabal:11:2: Tabs used as indentation at 11:2
hadrian: Encountered missing dependencies:
ghc-boot-th ==8.7.* && ==8.5

shakeArgsWith   0.000s    0%                           
Function shake  0.390s    3%  =                        
Database read   0.016s    0%                           
With database   0.001s    0%                           
Running rules   9.642s   95%  ======================== 
Total          10.048s  100%                           
Error when running Shake build system:
* _build/stage1/lib/bin/unlit
* OracleQ (PackageDataFile (Context {stage = Stage1, package = Package {pkgLanguage = Haskell, pkgType = Program, pkgName = "unlit", pkgPath = "utils/unlit"}, way = v}))
* _build/stage1/utils/unlit/setup-config
* _build/stage0/bin/ghc
* OracleQ (PackageDataFile (Context {stage = Stage0, package = Package {pkgLanguage = Haskell, pkgType = Program, pkgName = "ghc-bin", pkgPath = "ghc"}, way = v}))
* _build/stage0/ghc/setup-config
* _build/stage0/lib/package.conf.d/ghc-8.5.conf
* OracleQ (PackageDataFile (Context {stage = Stage0, package = Package {pkgLanguage = Haskell, pkgType = Library, pkgName = "ghc", pkgPath = "compiler"}, way = v}))
* _build/stage0/compiler/setup-config
* _build/stage0/lib/package.conf.d/template-haskell-2.14.0.0.conf
* OracleQ (PackageDataFile (Context {stage = Stage0, package = Package {pkgLanguage = Haskell, pkgType = Library, pkgName = "template-haskell", pkgPath = "libraries/template-haskell"}, way = v}))
* _build/stage0/libraries/template-haskell/setup-config
ExitFailure 1
```

I did observe that `binary` successfully built, which suggests that the Cabal problem has been fixed and this is some other breakage, right?

**Comment by snowleopard** [comment] 2018-06-26 18:52
@quasicomputational It does sound promising that the `binary` package was built successfully!

**Comment by quasicomputational** [comment] 2018-06-26 19:24
New failure:

```
$ hadrian/build.sh
Up to date
Up to date
Warning: libraries/text/text.cabal:4:1: The field "bug-reports" is specified
more than once at positions 4:1, 42:1
Warning: libraries/haskeline/haskeline.cabal:4:1: The field "category" is
specified more than once at positions 4:1, 10:1
Warning: utils/hpc/hpc-bin.cabal:11:2: Tabs used as indentation at 11:2
Warning: libraries/text/text.cabal:4:1: The field "bug-reports" is specified
more than once at positions 4:1, 42:1
| Run Ghc FindHsDependencies Stage1: libraries/ghc-compact/GHC/Compact.hs (and 1 more) => _build/stage1/libraries/ghc-compact/.dependencies.mk
| Remove file _build/stage1/libraries/ghc-compact/.dependencies.mk.bak
| Run Ghc CompileHs Stage1: libraries/ghc-compact/GHC/Compact.hs => _build/stage1/libraries/ghc-compact/build/GHC/Compact.p_o
| Run Ghc CompileHs Stage1: libraries/ghc-compact/GHC/Compact/Serialized.hs => _build/stage1/libraries/ghc-compact/build/GHC/Compact/Serialized.p_o
| Remove file _build/stage1/libraries/ghc-compact/build/libHSghc-compact-0.1.0.0_p.a
| Run Ar Pack Stage1: _build/stage1/libraries/ghc-compact/build/GHC/Compact.p_o (and 1 more) => _build/stage1/libraries/ghc-compact/build/libHSghc-compact-0.1.0.0_p.a
/usr/bin/ar: creating _build/stage1/libraries/ghc-compact/build/libHSghc-compact-0.1.0.0_p.a
/---------------------------------------------------------------------------------\
| Successfully built library 'ghc-compact' (Stage1, way p).                       |
| Library: _build/stage1/libraries/ghc-compact/build/libHSghc-compact-0.1.0.0_p.a |
| Library synopsis: In memory storage of deeply evaluated data structure.         |
\---------------------------------------------------------------------------------/
| Run Ghc CompileHs Stage1: libraries/ghc-compact/GHC/Compact.hs => _build/stage1/libraries/ghc-compact/build/GHC/Compact.o
| Run Ghc CompileHs Stage1: libraries/ghc-compact/GHC/Compact/Serialized.hs => _build/stage1/libraries/ghc-compact/build/GHC/Compact/Serialized.o
| Run Ld Stage1: _build/stage1/libraries/ghc-compact/build/GHC/Compact.o (and 1 more) => _build/stage1/libraries/ghc-compact/build/HSghc-compact-0.1.0.0.o
| Remove file _build/stage1/libraries/ghc-compact/build/libHSghc-compact-0.1.0.0.a
| Run Ar Pack Stage1: _build/stage1/libraries/ghc-compact/build/GHC/Compact.o (and 1 more) => _build/stage1/libraries/ghc-compact/build/libHSghc-compact-0.1.0.0.a
/usr/bin/ar: creating _build/stage1/libraries/ghc-compact/build/libHSghc-compact-0.1.0.0.a
/-------------------------------------------------------------------------------\
| Successfully built library 'ghc-compact' (Stage1, way v).                     |
| Library: _build/stage1/libraries/ghc-compact/build/libHSghc-compact-0.1.0.0.a |
| Library synopsis: In memory storage of deeply evaluated data structure.       |
\-------------------------------------------------------------------------------/
| Run Ghc FindHsDependencies Stage1: utils/hsc2hs/ATTParser.hs (and 9 more) => _build/stage1/utils/hsc2hs/.dependencies.mk
| Remove file _build/stage1/utils/hsc2hs/.dependencies.mk.bak
| Run Ghc CompileHs Stage1: _build/stage1/utils/hsc2hs/build/hsc2hs/autogen/Paths_hsc2hs.hs => _build/stage1/utils/hsc2hs/build/Paths_hsc2hs.o
| Run Ghc CompileHs Stage1: utils/hsc2hs/HSCParser.hs => _build/stage1/utils/hsc2hs/build/HSCParser.o
| Run Ghc CompileHs Stage1: utils/hsc2hs/Common.hs => _build/stage1/utils/hsc2hs/build/Common.o
| Run Ghc CompileHs Stage1: utils/hsc2hs/Flags.hs => _build/stage1/utils/hsc2hs/build/Flags.o
| Run Ghc CompileHs Stage1: utils/hsc2hs/C.hs => _build/stage1/utils/hsc2hs/build/C.o
| Run Ghc CompileHs Stage1: utils/hsc2hs/UtilsCodegen.hs => _build/stage1/utils/hsc2hs/build/UtilsCodegen.o
| Run Ghc CompileHs Stage1: utils/hsc2hs/ATTParser.hs => _build/stage1/utils/hsc2hs/build/ATTParser.o
| Run Ghc CompileHs Stage1: utils/hsc2hs/DirectCodegen.hs => _build/stage1/utils/hsc2hs/build/DirectCodegen.o
| Run Ghc CompileHs Stage1: utils/hsc2hs/CrossCodegen.hs => _build/stage1/utils/hsc2hs/build/CrossCodegen.o
| Run Ghc CompileHs Stage1: utils/hsc2hs/Main.hs => _build/stage1/utils/hsc2hs/build/Main.o
| Run Ghc LinkHs Stage1: _build/stage1/utils/hsc2hs/build/Main.o (and 9 more) => _build/stage1/bin/hsc2hs
_build/stage1/lib/../lib/i386-linux-ghc-8.7.20180626/rts-1.0/libHSrts-1.0.a(Adjustor.o):function createAdjustor: error: undefined reference to 'adjustorCode'
collect2: error: ld returned 1 exit status
`gcc' failed in phase `Linker'. (Exit code: 1)
shakeArgsWith   0.000s    0%                           
Function shake  0.407s    1%                           
Database read   0.349s    0%                           
With database   0.021s    0%                           
Running rules  38.289s   98%  =========================
Total          39.066s   99%                           
Error when running Shake build system:
* _build/stage1/bin/hsc2hs
user error (Development.Shake.cmd, system command failed
Command: _build/stage0/bin/ghc -Wall -hisuf hi -osuf o -hcsuf hc -static -hide-all-packages -no-user-package-db '-package-db _build/stage1/lib/package.conf.d' '-package-id base-4.12.0.0' '-package-id containers-0.6.0.1' '-package-id directory-1.3.2.3' '-package-id filepath-1.4.2' '-package-id process-1.6.3.0' -i -i_build/stage1/utils/hsc2hs/build -i_build/stage1/utils/hsc2hs/build/hsc2hs/autogen -iutils/hsc2hs/. -Iincludes -I_build/generated -I_build/stage1/utils/hsc2hs/build -I/home/sam2/src/ghc/_build/stage1/lib/i386-linux-ghc-8.7.20180626/process-1.6.3.0/include -I/home/sam2/src/ghc/_build/stage1/lib/i386-linux-ghc-8.7.20180626/unix-2.8.0.0/include -I/home/sam2/src/ghc/_build/stage1/lib/i386-linux-ghc-8.7.20180626/time-1.8.0.2/include -I/home/sam2/src/ghc/_build/stage1/lib/i386-linux-ghc-8.7.20180626/bytestring-0.10.8.2/include -I/home/sam2/src/ghc/_build/stage1/lib/i386-linux-ghc-8.7.20180626/base-4.12.0.0/include -I/home/sam2/src/ghc/_build/stage1/lib/i386-linux-ghc-8.7.20180626/integer-gmp-1.0.2.0/include -I/home/sam2/src/ghc/_build/stage1/lib/i386-linux-ghc-8.7.20180626/rts-1.0/include -I_build/generated -optc-I_build/generated -optP-include -optP_build/stage1/utils/hsc2hs/build/hsc2hs/autogen/cabal_macros.h -optc-U__i686 -optc-fno-stack-protector -optP-DIN_GHC_TREE -odir _build/stage1/utils/hsc2hs/build -hidir _build/stage1/utils/hsc2hs/build -stubdir _build/stage1/utils/hsc2hs/build -no-auto-link-packages -rtsopts -optl-lgmp -Wnoncanonical-monad-instances -optc-Werror=unused-but-set-variable -optc-Wno-error=inline _build/stage1/utils/hsc2hs/build/Main.o _build/stage1/utils/hsc2hs/build/C.o _build/stage1/utils/hsc2hs/build/Common.o _build/stage1/utils/hsc2hs/build/CrossCodegen.o _build/stage1/utils/hsc2hs/build/DirectCodegen.o _build/stage1/utils/hsc2hs/build/Flags.o _build/stage1/utils/hsc2hs/build/HSCParser.o _build/stage1/utils/hsc2hs/build/ATTParser.o _build/stage1/utils/hsc2hs/build/UtilsCodegen.o _build/stage1/utils/hsc2hs/build/Paths_hsc2hs.o -o _build/stage1/bin/hsc2hs -O2 -H32m -XHaskell2010 -ghcversion-file=/home/sam2/src/ghc/_build/generated/ghcversion.h
Exit code: 1
Stderr:
_build/stage1/lib/../lib/i386-linux-ghc-8.7.20180626/rts-1.0/libHSrts-1.0.a(Adjustor.o):function createAdjustor: error: undefined reference to 'adjustorCode'
collect2: error: ld returned 1 exit status
`gcc' failed in phase `Linker'. (Exit code: 1)
)
```

It does seem to have successfully built the stage-1 compiler, and this error looks unrelated. I think the Cabal thing is definitely fixed.

**Comment by snowleopard** [comment] 2018-06-26 19:28
@quasicomputational This means you've managed to build Stage1 GHC, so I think your fix works.

**Comment by alpmestan** [comment] 2018-06-26 21:02
Agreed, I don't think this new failure has anything to do with Cabal. @snowleopard In fact it looks rather similar to the findPtr (IIRC) error we've seen recently, I don't remember exactly how you fixed it but this is not a hard one is it?

**Comment by snowleopard** [comment] 2018-06-26 21:07
@alpmestan The `findPtr` issue is awaiting a GHC fix, see https://phabricator.haskell.org/D4846. I haven't yet done it because we're facing earlier failures. 

The issue encountered by @quasicomputational seems to be new.

**Comment by bgamari** [comment] 2018-06-26 21:42
> The issue encountered by @quasicomputational seems to be new.

Are you sure? It looks like @quasicomputational is building for i386; is this known to work?

**Comment by snowleopard** [comment] 2018-06-26 21:45
@bgamari By "new" I mean it's not related to any currently open Hadrian issues. It might be a non-issue too!

**Comment by bgamari** [comment] 2018-06-26 22:10
> @bgamari By "new" I mean it's not related to any currently open Hadrian issues.

Ahh, right.

> It might be a non-issue too!

Sadly it is an issue; building on i386 does work with the make build system. That being said, I think I know the cause here: neither i386 nor amd64 should use adjustors (e.g. `ArchHasAdjustorSupport=YES` in the make build system on these platforms).

**Comment by bgamari** [comment] 2018-06-26 22:12
Hmm, that being said on its surface Hadrian's logic (`useLibFFIForAdjustors`) looks correct here.

**Comment by alpmestan** [comment] 2018-06-26 22:42
@quasicomputational @snowleopard @bgamari `hadrian/build.sh -j4 --flavour=quickest` succeeded here on my nixos system, when using quasicomputational's Cabal branch. :tada:

**Comment by angerman** [comment] 2018-06-27 01:57
@quasicomputational
> The assumption in the Cabal code is that the CWD is the directory of the .cabal code, and it has been for a while. 

This was lifted maybe half a year or a bit more ago. I’m currently on mobile, so I can’t pull up the relevant cabal PR.

The idea was to drop the CWD global state from cabal, so that you can actually run multiple cabal functions in parallel without needing some form of global lock around CWD management.

This was one of the necessary changes to cabal to even allow dropping ghc-cabal in hadrian.

The make based system gets away with CWD changes as ghc-cabal is its own process for every package. In hadrian, hadrian calls cabal functions for every lib and runs potentially into CWD issues.

Hence when passing the `—cabal-file` flag cabal ow computes the base dir relative to that file and started looking up files relative to that as well.

The other change that happened around the same time was the `configure` script calling from outside of the pkg root to prevent source tree pollution.  You’ve just fixed that `\1` folder name bug ;-)

**Comment by alpmestan** [comment] 2018-06-27 07:46
So... we're good to go now, yeah?

**Comment by quasicomputational** [comment] 2018-06-27 09:14
I opened up #637 about the failure I saw since we all agree it's something separate to the Cabal problem.

As for being good to go: still need to merge haskell/cabal#5397 and then bump GHC's Cabal submodule. I don't think there's anything to do on the Hadrian side except to continue working around it by making sure the Cabal submodule's not set to a broken commit.

**Comment by snowleopard** [comment] 2018-06-27 14:54
Many thanks all! 

@alpmestan Yes, good idea. Presumably it may take some time for the Cabal patch to reach GHC HEAD. Would you like to submit the PR or shall I do that? Happy either way :)

**Comment by alpmestan** [comment] 2018-06-27 15:29
@snowleopard I'll do it.

**Comment by alpmestan** [comment] 2018-06-27 15:41
PR is up: https://github.com/snowleopard/hadrian/pull/640

**Comment by snowleopard** [comment] 2018-06-28 13:21
Thanks to @alpmestan we now have a workaround in CI to use @quasicomputational's patch. I'll keep this issue open so we remember to switch CI back to GHC HEAD.

**Comment by quasicomputational** [comment] 2018-07-08 12:29
I've pushed the fix to Cabal master and opened https://ghc.haskell.org/trac/ghc/ticket/15353 asking for a submodule bump. Once that's done, the only thing left is ripping out the CI hack.

**Comment by alpmestan** [comment] 2018-07-08 19:52
Great, thank you!

**Comment by mgsloan** [comment] 2018-07-19 08:48
Because finding the workaround above took me a bit of time, here it is with an H1 above it, and as the last comment on the issue (currently)

# The Workaround: patched Cabal submodule

```
cd libraries/Cabal/
git remote add quasicomputational https://github.com/quasicomputational/cabal.git
git fetch quasicomputational
git checkout cwd-independent-check
cd ../../
```

**Comment by alpmestan** [comment] 2018-07-28 04:39
@bgamari This issue is fixed by a Cabal PR that has hit the master branch of Cabal, but the Cabal submodule has not been updated yet. Are there somewhat strict rules for bumping `libraries/Cabal/` or should I just feel free to go ahead and create a diff? Or perhaps we need @hvr or others to be involved.

**Comment by alpmestan** [comment] 2018-07-30 15:50
I opened https://phabricator.haskell.org/D5024 to bump the submodule. Let's see how that goes.

**Closed** 2018-07-31 21:45 UTC
Labels: bug-upstream, infrastructure

**Comment by snowleopard** [comment] 2018-07-31 21:48
Many thanks to everyone, this is now resolved! 🎉
